name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update -y
    - name: Install packages
      run: sudo apt-get install -y python3-jinja2 python3-matplotlib
    - name: Build (debug)
      run: ./build-debug.sh
    - name: Test (debug)
      run: ./test.py
    - name: Build (release)
      run: ./build.sh
    - name: Test (release)
      run: ./test.py
    - name: Test library (first pass)
      run: ./test-lib.py
    - name: Test library (reusing results)
      run: ./test-lib.py
